version: 2.1

commads:
  install-aws-cli:
    steps:
      - run: echo instalando cli
      # Descarga todo el repo donde este
      # - checkout

jobs:
  install-dependencies:
    docker:
      - image: cimg/base:stable
    steps:
      - install-aws-cli
      # Puede ser un step del Job o de un comando
      - checkout
      - run: ls -la

workflows:
  install-workflow:
    jobs:
      - install-dependencies
