version: 2.1

# Los parametros nos da la flexibilidad de dar diferentes valores 
# esto nos permite que se ejecute de foma diferente segun el valor
parameters:
  # Nombre del parametro
  nombre:
    # Tipo de parametro
    type: string
    # Valor por defecto
    default: log

# los jobs son tareas que se ejecutan cuando son llamadas
jobs:
  # Nombre de la tarea
  saluda:
    # El entorno donde se ejecuta
    docker:
      # La imagen donde ejecuta los pasos
      - image: cimg/base:stable
    # Los pasos que va a ejecutar
    steps:
      # Es pipline.parameters ya que es un parametro definido en el pipeline se define '<<>>'
      - run: echo hello << pipeline.parameters.nombre >>
  # Se pueden defini varias tareas
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      # Se pueden ejecutar varios pasos
      - run: echo adios
      - run: echo adios de verdad

workflows:
  paramworkflow:
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda
