version: 2.1

commands:
  install-cli:
    steps:
      - run: echo install cli
      # Descarga todo el repo donde este
      # - checkout

jobs:
  install-dependencies:
    docker:
      - image: cimg/base:stable
    steps:
      - install-cli
      # Se puede llamar como step de un comando o de un job
      - checkout
      - run: ls -lha

workflows:
  install-workflow:
    jobs:
      - install-dependencies
