version: 2.1

# Parameters
parameters:
  newname:
    type: string
    default: Pako

# Comandos reutilizables
commands:
  # Parametrizar comandos
  parameters:
    timenumber:
      type: integer
      default: 5
  # Nombre del comando
  fecha_hora:
    steps:
      - run: date && sleep 10
  say_hi:
    steps:
      - run: echo << parameters.timenumber >>

jobs:
  hello:
    docker:
      - image: ubuntu:latest
    steps:
      # Llamada al comando por nombre
      - fecha_hora
      - run: echo Hello
      - fecha_hora
  bye:
    docker:
      - image: cimg/base:stable
    steps:
      # Variable a nivel pipline
      - run: echo Hello << pipeline.parameters.newname >>
      - say_hi:
          timenumber: 10

workflows:
  say:
    jobs:
      - hello:
          name: say_hello
      - bye:
          name: say_bye
          requires:
            - say_hello
