version: 2.1

commads:
  install-cli:
    - run: echo istall cli
    # Descarga todo el repo donde este
    # - checkout

jobs:
  install-dependecies:
    docker:
      - image: cimg/base:stable
    steps:
      - install-cli
      # Puede ser un step del Job o de un comando
      - checkout
      - run: ls -lha

workflows:
  install-workflow:
    jobs:
      - install-dependencies
